### ISSUE TITLE
Error on OS X

### ISSUE THREAD

**Issue by marcusbuffett** [liangguohuan/fzf-marker#1]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]

I get the above when I try to run fzf-marker. Installed manually. Let me know if you need any more info!

**Comment by marcusbuffett** [comment]
Also the sed replacement for color doesn't work with OS X's sed, was able to get it to work by replacing the call with a call to the gnutil sed.
Full fix for os x ended up being:
```
brew install grep --with-default-names
brew install gnutil
# Replace sed call in fzf-marker.plugin.zsh with gsed
```

**Comment by liangguohuan** [comment]
sorry about that. I  don’t have a MacBook, so i can’t debug it. It’s been tested in zsh in Ubuntu.

**Comment by liangguohuan** [comment]
Now, I got a macbook, and I found the solution. 

```
# brew install grep
# ln -s /usr/local/Cellar/grep/3.3/bin/ggrep /usr/local/bin/grep
```
